#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'apt', '1.10.0'
cookbook 'ntp'
cookbook 'timezone', '0.0.1'
cookbook 'networking_basic',
  :github => 'fred/fredz_cookbooks'

cookbook 'vim'

cookbook 'apache2'
cookbook 'mysql'
cookbook 'database'
cookbook 'php'

cookbook 'typo3',
  :github => 'irnnr/chef-typo3'
